name: ChatColors
main: com.zFlqw.chatcolors.ChatColors
version: 1.1.1
api-version: 1.18
author: zFlqw
description: >
  A lightweight Minecraft plugin that allows players to use color codes (&) in chat messages.
  Supports configurable colors and multi-language messages.
commands:
  chatcolor:
    description: Manage ChatColor plugin commands
    usage: /chatcolor <reload|set> [color]
    permission: chatcolor.use
    permission-message: You do not have permission to use this command.
    aliases: [cc]
permissions:
  chatcolor.use:
    description: Allows use of chatcolor commands
    default: true
  chatcolor.admin:
    description: Allows admin to use the reload command to reload configuration.
    default: op